### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by luiscarlin**
Just some typos in the README.md

### CODE REVIEW

**Comment by imarios** [comment]
Looks good! thank you @luiscarlin! Can you squash the 3 commits into one?

**Comment by luiscarlin** [comment]
@imarios Done.

**Comment by luiscarlin** [comment]
@imarios Do I need to do anything else to get this pull request merged?

**Comment by imarios** [comment]
@luiscarlin I asked @eucuepo if he can give me collaborator access so I can merge PR, but I wasn't able to get hold of him. Maybe he was on vacation. @eucuepo Hi :)

**Comment by imarios** [comment]
Apologies for the delay @luiscarlin! Thank you so much for the edits.

**Pull request merged**
