### PR TITLE
Create .gitattributes

### PR DESCRIPTION
**Pull request by caddac**
Solves #5 & #6. Forces lf line endings regardless of users eof setting, guaranteeing the .sh files run properly in the vagrant vms on windows platforms that checkout crlf

### CODE REVIEW

**Comment by imarios** [comment]
@caddac awesome! Does it also solves the issue with the configuration files? Was the problem only with *.sh scripts?

**Comment by caddac** [comment]
Once I added this file to my fork and re-cloned I was able to follow the readme instructions exactly to get a working producer/consumer via Powershell/ssh. I think the problem is that I have git configured to checkout crlf and commit lf, but for the files put onto the vagrant vms I need lf line endings. I haven't tested it but this change shouldn't affect non-windows users.

**Comment by caddac** [comment]
To specifically answer your questions, vagrant is reading the configuration files, only .sh files needed lf line endings I think.

**Comment by imarios** [comment]
Looks good to me! @eucuepo will take a look and comment/merge

**Comment by caddac** [comment]
@eucuepo Any update on getting this merged?

**Pull request merged**
